PIDs:
  X:
    kp: 30.0
    kd: 20.0
    ki: 2.0
    minOutput: -15.0
    maxOutput: 15.0
    integratorMin: -0.1
    integratorMax: 0.1
    bias: 1
  Y:
    kp: -30.0
    kd: -10.0
    ki: -2.0
    minOutput: -30.0
    maxOutput: 15.0
    integratorMin: -1
    integratorMax: 1
    bias: -20
  Z:
    kp: 5000.0
    kd: 6000.0
    ki: 1200.0
    minOutput: 10000.0
    maxOutput: 60000.0
    integratorMin: -1000.0
    integratorMax: 1000.0
    bias: 2000
  Yaw:
    kp: 2.0
    kd: 0.0
    ki: 1.0
    minOutput: -4.0
    maxOutput: 4.0
    integratorMin: -1
    integratorMax: 1
    bias: 0
